version: '3'
services:
  model:
    build: ./model
    container_name: model_container
    volumes:
      - model_data:/model
    networks:
      - app_network

  app:
    build: ./app
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - model
    networks:
      - app_network
    volumes:
      - model_data:/app/model

volumes:
  model_data:  # Volume partagé pour stocker le modèle

networks:
  app_network:  # Créer un réseau commun pour que les services puissent se parler
    driver: bridge
